//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterimobelWS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppDTEntities : DbContext
    {
        public AppDTEntities()
            : base("name=AppDTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<GETSURVEY> GETSURVEY { get; set; }
        public virtual DbSet<NOTVISIT> NOTVISIT { get; set; }
        public virtual DbSet<INSTALLER> INSTALLER { get; set; }
        public virtual DbSet<SURVEY> SURVEY { get; set; }
        public virtual DbSet<SURVEY_CUESTION> SURVEY_CUESTION { get; set; }
        public virtual DbSet<SURVEY_CUESTION_ANSWARE> SURVEY_CUESTION_ANSWARE { get; set; }
        public virtual DbSet<vis_survey> vis_survey { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VISITA_ASSIGN> VISITA_ASSIGN { get; set; }
        public virtual DbSet<vis_VISITA_CUSTOMER> vis_VISITA_CUSTOMER { get; set; }
        public virtual DbSet<vis_Assigned_Visit> vis_Assigned_Visit { get; set; }
        public virtual DbSet<VISITA_REGISTRO> VISITA_REGISTRO { get; set; }
        public virtual DbSet<SURVEY_CUESTION_OP> SURVEY_CUESTION_OP { get; set; }
        public virtual DbSet<vis_Survey_Data> vis_Survey_Data { get; set; }
        public virtual DbSet<vis_VISITA_NOTVISIT> vis_VISITA_NOTVISIT { get; set; }
        public virtual DbSet<vis_VISITA_REGISTRO> vis_VISITA_REGISTRO { get; set; }
    }
}
